"""Initial schema: all tables

Revision ID: 8874b37b5d31
Revises: 
Create Date: 2026-02-25 15:29:51.402102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8874b37b5d31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('actual_value', sa.String(length=50), nullable=True),
    sa.Column('forecast_value', sa.String(length=50), nullable=True),
    sa.Column('previous_value', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ee_currency', 'economic_events', ['currency'], unique=False)
    op.create_index('idx_ee_datetime', 'economic_events', ['event_datetime'], unique=False)
    op.create_table('historical_ohlcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'timeframe', 'timestamp')
    )
    op.create_index('idx_ho_pair_tf_ts', 'historical_ohlcv', ['pair', 'timeframe', 'timestamp'], unique=False)
    op.create_table('system_default_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('api_key_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('default_model', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider')
    )
    op.create_table('chart_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('chart_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pair')
    )
    op.create_table('daily_notification_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('send_time_utc', sa.Time(), nullable=True),
    sa.Column('include_pnl', sa.Boolean(), nullable=True),
    sa.Column('include_trades', sa.Boolean(), nullable=True),
    sa.Column('include_guards', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('exchange_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange_type', sa.String(length=20), nullable=False),
    sa.Column('api_key_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('api_secret_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exchange_type')
    )
    op.create_table('market_watch_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mwc_user_id', 'market_watch_configs', ['user_id'], unique=False)
    op.create_table('notification_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ne_user_id', 'notification_emails', ['user_id'], unique=False)
    op.create_table('traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_name', sa.String(length=40), nullable=False),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('capital_jpy', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('order_unit_lots', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('strategy_text', sa.Text(), nullable=True),
    sa.Column('notify_email', sa.String(length=255), nullable=True),
    sa.Column('notify_on_entry', sa.Boolean(), nullable=True),
    sa.Column('notify_on_stop', sa.Boolean(), nullable=True),
    sa.Column('notify_on_error', sa.Boolean(), nullable=True),
    sa.Column('notify_on_exit', sa.Boolean(), nullable=True),
    sa.Column('notify_on_target', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_traders_user_id', 'traders', ['user_id'], unique=False)
    op.create_table('ai_decision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('system_prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('parsed_result', sa.JSON(), nullable=True),
    sa.Column('parse_success', sa.Boolean(), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('adopted', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adl_timestamp', 'ai_decision_logs', ['timestamp'], unique=False)
    op.create_index('idx_adl_trader_id', 'ai_decision_logs', ['trader_id'], unique=False)
    op.create_index('idx_adl_user_id', 'ai_decision_logs', ['user_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('avg_rr_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_br_user_id', 'backtest_runs', ['user_id'], unique=False)
    op.create_table('config_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('config_type', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=True),
    sa.Column('config_before', sa.JSON(), nullable=False),
    sa.Column('config_after', sa.JSON(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cc_changed_at', 'config_changes', ['changed_at'], unique=False)
    op.create_index('idx_cc_trader_id', 'config_changes', ['trader_id'], unique=False)
    op.create_index('idx_cc_user_id', 'config_changes', ['user_id'], unique=False)
    op.create_table('model_stage_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trader_id', 'stage')
    )
    op.create_index('idx_msc_trader_id', 'model_stage_configs', ['trader_id'], unique=False)
    op.create_index('idx_msc_user_id', 'model_stage_configs', ['user_id'], unique=False)
    op.create_table('pipeline_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('output_snapshot', sa.JSON(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('elapsed_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pl_execution_id', 'pipeline_logs', ['execution_id'], unique=False)
    op.create_index('idx_pl_stage', 'pipeline_logs', ['stage'], unique=False)
    op.create_index('idx_pl_trader_id_timestamp', 'pipeline_logs', ['trader_id', 'timestamp'], unique=False)
    op.create_index('idx_pl_user_id', 'pipeline_logs', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('exchange_position_id', sa.String(length=100), nullable=True),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tp_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('sl_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('break_even_applied', sa.Boolean(), nullable=True),
    sa.Column('trail_active', sa.Boolean(), nullable=True),
    sa.Column('trail_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_positions_pair', 'positions', ['pair'], unique=False)
    op.create_index('idx_positions_trader_id', 'positions', ['trader_id'], unique=False)
    op.create_index('idx_positions_user_id', 'positions', ['user_id'], unique=False)
    op.create_table('safeguard_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trader_id')
    )
    op.create_index('idx_sgc_trader_id', 'safeguard_configs', ['trader_id'], unique=False)
    op.create_index('idx_sgc_user_id', 'safeguard_configs', ['user_id'], unique=False)
    op.create_table('safeguard_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('guard_id', sa.String(length=10), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sgl_result', 'safeguard_logs', ['result'], unique=False)
    op.create_index('idx_sgl_trader_id_timestamp', 'safeguard_logs', ['trader_id', 'timestamp'], unique=False)
    op.create_index('idx_sgl_user_id', 'safeguard_logs', ['user_id'], unique=False)
    op.create_table('simulation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sh_user_id', 'simulation_history', ['user_id'], unique=False)
    op.create_table('trade_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('realized_pnl_pips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rr_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tp_pips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sl_pips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('hold_duration_min', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_th_closed_at', 'trade_history', ['closed_at'], unique=False)
    op.create_index('idx_th_pair', 'trade_history', ['pair'], unique=False)
    op.create_index('idx_th_trader_id', 'trade_history', ['trader_id'], unique=False)
    op.create_index('idx_th_user_id', 'trade_history', ['user_id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('realized_pnl_pips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rr_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=True),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('pipeline_log_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bt_backtest_run_id', 'backtest_trades', ['backtest_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bt_backtest_run_id', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index('idx_th_user_id', table_name='trade_history')
    op.drop_index('idx_th_trader_id', table_name='trade_history')
    op.drop_index('idx_th_pair', table_name='trade_history')
    op.drop_index('idx_th_closed_at', table_name='trade_history')
    op.drop_table('trade_history')
    op.drop_index('idx_sh_user_id', table_name='simulation_history')
    op.drop_table('simulation_history')
    op.drop_index('idx_sgl_user_id', table_name='safeguard_logs')
    op.drop_index('idx_sgl_trader_id_timestamp', table_name='safeguard_logs')
    op.drop_index('idx_sgl_result', table_name='safeguard_logs')
    op.drop_table('safeguard_logs')
    op.drop_index('idx_sgc_user_id', table_name='safeguard_configs')
    op.drop_index('idx_sgc_trader_id', table_name='safeguard_configs')
    op.drop_table('safeguard_configs')
    op.drop_index('idx_positions_user_id', table_name='positions')
    op.drop_index('idx_positions_trader_id', table_name='positions')
    op.drop_index('idx_positions_pair', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_pl_user_id', table_name='pipeline_logs')
    op.drop_index('idx_pl_trader_id_timestamp', table_name='pipeline_logs')
    op.drop_index('idx_pl_stage', table_name='pipeline_logs')
    op.drop_index('idx_pl_execution_id', table_name='pipeline_logs')
    op.drop_table('pipeline_logs')
    op.drop_index('idx_msc_user_id', table_name='model_stage_configs')
    op.drop_index('idx_msc_trader_id', table_name='model_stage_configs')
    op.drop_table('model_stage_configs')
    op.drop_index('idx_cc_user_id', table_name='config_changes')
    op.drop_index('idx_cc_trader_id', table_name='config_changes')
    op.drop_index('idx_cc_changed_at', table_name='config_changes')
    op.drop_table('config_changes')
    op.drop_index('idx_br_user_id', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index('idx_adl_user_id', table_name='ai_decision_logs')
    op.drop_index('idx_adl_trader_id', table_name='ai_decision_logs')
    op.drop_index('idx_adl_timestamp', table_name='ai_decision_logs')
    op.drop_table('ai_decision_logs')
    op.drop_index('idx_traders_user_id', table_name='traders')
    op.drop_table('traders')
    op.drop_index('idx_ne_user_id', table_name='notification_emails')
    op.drop_table('notification_emails')
    op.drop_index('idx_mwc_user_id', table_name='market_watch_configs')
    op.drop_table('market_watch_configs')
    op.drop_table('exchange_configs')
    op.drop_table('daily_notification_configs')
    op.drop_table('chart_configs')
    op.drop_table('ai_model_configs')
    op.drop_table('users')
    op.drop_table('system_default_prompts')
    op.drop_index('idx_ho_pair_tf_ts', table_name='historical_ohlcv')
    op.drop_table('historical_ohlcv')
    op.drop_index('idx_ee_datetime', table_name='economic_events')
    op.drop_index('idx_ee_currency', table_name='economic_events')
    op.drop_table('economic_events')
    # ### end Alembic commands ###
